启用CookieWeb: true
CookieWeb地址: http://127.0.0.1:13579/LittlePaimon/cookie
绑定二维码以链接形式发送: false
图片资源缓存开关: true
禁用重启时修改群名片群列表: []
模拟抽卡群冷却: 30
模拟抽卡群员冷却: 60
模拟抽卡单次最多十连数: 5
米游币自动获取开关: true
米游币开始执行时间(小时): 8
米游币开始执行时间(分钟): 0
米游社自动签到开关: false
米游社签到开始时间(小时): 0
米游社签到开始时间(分钟): 5
实时便签检查开关: true
实时便签停止检查开始时间: 0
实时便签停止检查结束时间: 6
实时便签检查间隔: 16
ys自动更新小时: 24
ysa自动更新小时: 24
ysd自动更新小时: 6
云原神自动签到开关: true
云原神签到时间(小时): 7
启用好友和群请求通知: true
自动接受好友请求: false
自动接受群邀请: false
启用好友和群欢迎消息: true
启用网页截图权限: false
原神猜语音时间: 30
启用Web端: true
Web端管理员密码: admin
Web端token密钥: 49c294d32f69b732ef6447c18379451ce1738922a75cd1d4812ef150318a2ed0
Web端主题: default
启用命令别名: true
github资源地址: https://github.cherishmoon.fun/
